### ISSUE TITLE
Cannot redefine property: CLIP_NAME

### ISSUE THREAD

**Issue by fax1ty** [pmndrs/drei#1379]
- `three` version: 0.148.0
- `@react-three/fiber` version: 8.10.0
- `@react-three/drei` version: 9.53.0
- `node` version: v18.13.0
- `yarn` version: 1.22.19

### Problem description:

```
useAnimations.js:15 Uncaught TypeError: Cannot redefine property: CLIP_NAME
    at Function.defineProperty (<anonymous>)
    at useAnimations.js:15:34
    at Array.forEach (<anonymous>)
    at useAnimations.js:15:11
    at mountState (react-reconciler.development.js:8040:20)
    at Object.useState (react-reconciler.development.js:8768:16)
    at Object.useState (react.development.js:1622:21)
    at useAnimations (useAnimations.js:13:23)
    at Map (index.tsx:26:23)
    at renderWithHooks (react-reconciler.development.js:7363:18)
```

### Relevant code:

```ts
const ref = useRef<THREE.Group | null>(null);
const { animations, scene } = useGLTF(mapModel) as GLTF;
const { actions } = useAnimations(animations, ref);
  
return <primitive ref={ref} object={scene} />;
```

**Comment by enijar** [comment]
@fax1ty this happened to me. I noticed that my exported GLTF file had duplicate animations (six instead of three in my case):

![Screenshot 2023-04-11 at 17 16 40](https://user-images.githubusercontent.com/5284715/231225456-2de2ec9b-e842-4f5b-be96-86fbfc37050e.png)
