### ISSUE TITLE
bug: storybook - webpack - digital envelope routines::unsupported

### ISSUE THREAD

**Issue by frankievx** [pmndrs/drei#1424]
- `three` version: "^0.149.0"
- `@react-three/fiber` version: "^8.0.8"
- `@react-three/drei` version: "0.0.0-semantic-release"
- `node` version: v18.16.0
- `npm` (or `yarn`) version: 9.5.1

### Problem description:
After forking the repository, cloning, and installing dependencies. Ran into an issue with the "npm run storybook" script.  The error I encountered is identified as a webpack issue involving openSSL found here - https://github.com/webpack/webpack/issues/14532

The solution in the thread is to use the legacy openssl provider. 

### Relevant code:

```json
{ "scripts": "storybook": "start-storybook -p 6006" }
```

### Suggested solution:

```json
{ "scripts": "storybook": "NODE_OPTIONS=\"--openssl-legacy-provider\" start-storybook -p 6006" }
```

**Comment by abernier** [comment]
this error is related to node 18 (was ok with node 16):

```
$ yarn storybook
yarn run v1.22.19
$ start-storybook -p 6006
info @storybook/react v6.5.14
info 
info => Loading presets
info => Serving static files from ././.storybook/public at /
info => Loading custom manager config
info => Using implicit CSS loaders
info => Loading custom manager config
info => Using default Webpack4 setup
Starting type checking service...
10% building 1/2 modules 1 active /Users/abernier/Sites/drei/node_modules/@storybook/addon-actions/preview.js-generated-config-entry.jsnode:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/abernier/Sites/drei/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/abernier/Sites/drei/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/abernier/Sites/drei/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/abernier/Sites/drei/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/abernier/Sites/drei/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/abernier/Sites/drei/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/abernier/Sites/drei/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /Users/abernier/Sites/drei/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /Users/abernier/Sites/drei/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.16.0
```
```
