### ISSUE TITLE
SpriteAnimator TypeError: Cannot read properties of undefined (reading 'sourceSize')

### ISSUE THREAD

**Issue by jakke-korpelainen** [pmndrs/drei#1473]
I've started receiving this error after a while of succesfully working with the new sprites. Started this sandbox today so versions should be @latest of today. Noteworthy is that I'm running this inside nextjs which might do some funky caching, however I'm running this in a [NoSsr ](https://stackoverflow.com/a/57173209/1493524) component which should force this to run in client anyway. 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'sourceSize')
    at modifySpritePosition (SpriteAnimator.js:207:7)
    at eval (SpriteAnimator.js:74:1)
```

Below is roughly my implementation and the bat sprite is a super simple 128x32 with 4 frames of which the first frame is skipped and the rest is looped. The sprite is like this ![this sprite](https://github.com/pmndrs/drei/assets/3626319/3296c74b-0330-4a0c-bc2c-76ae551fcd6a). I'm using the SpriteAnimator component in a "left to right semi-automatical" configuration as you see below.

```
<SpriteAnimator
  position={[1, 2, 1]}
  scale={[2, 2, 2]}
  startFrame={1}
  autoPlay={true}
  fps={12}
  loop={true}
  numberOfFrames={3}
  alphaTest={0.01}
  textureImageURL={"/sprites/bat.png"}
/>
```

Thanks in advance! I'll gladly supply more information if required.

**Comment by jakke-korpelainen** [comment]
Might have been due to misconfiguration, but closing it for now until it happens again.
