### ISSUE TITLE
Marching cubes crash (TypeError: Cannot read properties of null)

### ISSUE THREAD

**Issue by Schlipak** [pmndrs/drei#1517]
- `three` version: 153
- `@react-three/fiber` version: 8.13.3
- `@react-three/drei` version: 9.74.16
- `node` version: v18.14.2
- `npm` (or `yarn`) version: yarn v1.22.19

### Problem description:

The `MarchingCubes` and related components (Cube and Plane) crash on usage:

> Uncaught TypeError: Cannot read properties of null (reading 'visible')
> Uncaught TypeError: Cannot read properties of null (reading 'flatShading') (repeating each frame)

<details><summary>Full trace</summary>
<pre>
Uncaught TypeError: Cannot read properties of null (reading 'visible')
    at projectObject (three.module.js:29146:28)
    at projectObject (three.module.js:29162:5)
    at WebGLRenderer.render (three.module.js:28939:4)
    at render$1 (index-76c68185.esm.js:1513:61)
    at loop (index-76c68185.esm.js:1537:19)
</pre>

<pre>
Uncaught TypeError: Cannot read properties of null (reading 'flatShading')
    at posnormtriv (MarchingCubes.js:206:26)
    at polygonize (MarchingCubes.js:189:9)
    at MarchingCubes.update (MarchingCubes.js:430:13)
    at Object.current (MarchingCubes.js:23:19)
    at render$1 (index-76c68185.esm.js:1510:22)
    at loop (index-76c68185.esm.js:1537:19)
</pre>
</details>

Inspecting the trace shows the issue seems to be coming from Three attempting to access properties on the object's material, which is null.

### Relevant code:

The crash happens with a minimal Vite TypeScript application, using the readme example code for marching cubes verbatim:

App.tsx

```js
import { Canvas } from '@react-three/fiber';
import { OrbitControls } from '@react-three/drei';

import Metaballs from './components/Metaballs';

const canvasStyles: React.CSSProperties = {
  position: 'fixed',
  top: 0,
  left: 0,
  width: '100vw',
  height: '100vh',
};

function App() {
  return (
    <Canvas
      camera={{ position: [0, 0, 5], fov: 45 }}
      shadows
      style={canvasStyles}
    >
      <Metaballs />
      <OrbitControls makeDefault />
    </Canvas>
  );
}

export default App;
```

Metaballs.tsx

```js
import { MarchingCube, MarchingCubes, MarchingPlane } from '@react-three/drei';
import { Color } from 'three';

const Metaballs: React.FC = () => {
  return (
    <MarchingCubes
      resolution={50}
      maxPolyCount={20000}
      enableUvs={false}
      enableColors={true}
    >
      <MarchingCube
        strength={0.5}
        subtract={12}
        color={new Color('#f0f')}
        position={[0.5, 0.5, 0.5]}
      />

      <MarchingPlane planeType="y" strength={0.5} subtract={12} />
    </MarchingCubes>
  );
};

export default Metaballs;
```

**Comment by Schlipak** [comment]
Solved: You need to specify a material as a child of MarchingCubes, as it doesn't set a default like the THREE primitives.
