### ISSUE TITLE
I do not know if this is a Bug but I think that drei is not reaching some artifacts

### ISSUE THREAD

**Issue by SalvatoreB98** [pmndrs/drei#1535]
### What is your question:
 Is it normal that I have this error
Uncaught Error: Could not load potsdamer_platz_1k.hdr: Failed to fetch)     at Object.onError (index-76c68185.esm.js:1642:36)     at three.module.js:41956:39

when I import Environment example:
<Environment preset="city" />

**Comment by testforworkhh** [comment]
> 

have the same error. Update version package to 9.77.4.

**Comment by realsammyt** [comment]
Older versions are calling a broken CDN. You can use local files or update to a newer version of Drei that points to the prmndrs CDN.
