### ISSUE TITLE
Unexpected token error when importing

### ISSUE THREAD

**Issue by Alex23925** [pmndrs/drei#159]
I am trying to import orbit controls but I get this error when importing it 
(tried:
import { OrbitControls} from '@react-three/drei';
and
import { OrbitControls} from 'drei'):

```
C:\Users\User\Desktop\webdev\r3f\r3f-lighting\node_modules\three\examples\jsm\lines\LineGeometry.js:2
import { LineSegmentsGeometry } from "../lines/LineSegmentsGeometry.js";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
\Desktop\webdev\r3f\r3f-lighting\node_modulesoader.js:692:17)\drei\index.cjs.js:11:20)                    js:25:18)
    at Module._compile (internal/modules/cjs/\Desktop\webdev\r3f\r3f-lighting\node_modules\dreloader.js:778:30)
    at Object.Module._extensions..js (internaloader.js:778:30)l/modules/cjs/loader.js:789:10)

```

I assume I have to go directly into the library and fix something but I thought id ask here because no tutorials ive seen run into this issue and react-three-fiber as well as three work perfectly fine. Im also using nextjs if thats messing with it somehow

**Comment by ebzeal** [comment]
Hi @Alex23925 , how did you solve this? I am having the same issues and I believe it is because of Nextjs

**Comment by joshuaellis** [comment]
@ebzeal  this is a nextjs issue. You have to either import the components dynamically with ssr: false or use next-transpile-modules

**Comment by williaster** [comment]
linking to a related issue with more detailed workaround suggestion

https://github.com/pmndrs/drei/issues/253#issuecomment-764979499
