### ISSUE TITLE
Environment Component is broken

### ISSUE THREAD

**Issue by jamesryan-dev** [pmndrs/drei#1595]
"three": "^0.138.2"
 "@react-three/fiber": "^7.0.26",
"@react-three/drei": "^8.11.3",
   
╰─ node -v
v16.14.0
╰─ yarn -v
1.22.17

### Problem description:

Spun up an old project and have updated the packages. My model is spinning and loading correctly when I remove the drie Environment component. Getting 404's on the preset environments. 

```

const [enviro, setEnviro] = useState("studio");

 <Environment preset={enviro} /> 
```

simple breakdown of the component. 

Errors on localhost:

```
three.module.js:39510     GET https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/hdris/studio-small-3/studio_small_03_1k.hdr net::ERR_SSL_UNRECOGNIZED_NAME_ALERT
load @ three.module.js:39510
load @ three.module.js:40049
load @ RGBELoader.js:247
eval @ react-three-fiber.esm.js:1654
eval @ react-three-fiber.esm.js:1654
eval @ react-three-fiber.esm.js:1654
handleAsset @ index.js:24
useAsset @ index.js:69
useLoader @ react-three-fiber.esm.js:1669
EnvironmentCube @ Environment.js:108
renderWithHooks @ react-reconciler.development.js:6412
mountIndeterminateComponent @ react-reconciler.development.js:9238
beginWork @ react-reconciler.development.js:10476
beginWork$1 @ react-reconciler.development.js:16507
performUnitOfWork @ react-reconciler.development.js:15337
workLoopSync @ react-reconciler.development.js:15268
renderRootSync @ react-reconciler.development.js:15231
performSyncWorkOnRoot @ react-reconciler.development.js:14821
eval @ react-reconciler.development.js:2546
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority @ react-reconciler.development.js:2495
flushSyncCallbackQueueImpl @ react-reconciler.development.js:2541
flushSyncCallbackQueue @ react-reconciler.development.js:2528
scheduleUpdateOnFiber @ react-reconciler.development.js:14421
updateContainer @ react-reconciler.development.js:18229
render @ react-three-fiber.esm.js:1787
eval @ react-three-fiber.esm.js:1565
commitHookEffectListMount @ react-dom.development.js:20573
commitLifeCycles @ react-dom.development.js:20634
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
eval @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
callback @ web.js:78
later @ index.js:27
setTimeout (async)
debounced @ index.js:38
index.js:12 Uncaught Could not load studio-small-3/studio_small_03_1k.hdr: Failed to fetch
handleAsset @ index.js:12
useAsset @ index.js:69
useLoader @ react-three-fiber.esm.js:1669
EnvironmentCube @ Environment.js:108
renderWithHooks @ react-reconciler.development.js:6412
mountIndeterminateComponent @ react-reconciler.development.js:9238
beginWork @ react-reconciler.development.js:10476
callCallback @ react-reconciler.development.js:12184
invokeGuardedCallbackDev @ react-reconciler.development.js:12233
invokeGuardedCallback @ react-reconciler.development.js:12292
beginWork$1 @ react-reconciler.development.js:16531
performUnitOfWork @ react-reconciler.development.js:15337
workLoopSync @ react-reconciler.development.js:15268
renderRootSync @ react-reconciler.development.js:15231
performSyncWorkOnRoot @ react-reconciler.development.js:14821
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
next-dev.js:32 The above error occurred in the <EnvironmentCube> component:

    at EnvironmentCube (webpack-internal:///./node_modules/@react-three/drei/core/Environment.js:104:3)
    at Environment (webpack-internal:///./node_modules/@react-three/drei/core/Environment.js:27:16)
    at Suspense
    at Suspense
    at ErrorBoundary (webpack-internal:///./node_modules/@react-three/fiber/dist/react-three-fiber.esm.js:1550:5)
    at Provider (webpack-internal:///./node_modules/@react-three/fiber/dist/react-three-fiber.esm.js:1838:3)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
window.console.error @ next-dev.js:32
logCapturedError @ react-reconciler.development.js:11782
update.payload @ react-reconciler.development.js:11830
getStateFromUpdate @ react-reconciler.development.js:3483
processUpdateQueue @ react-reconciler.development.js:3631
updateClassInstance @ react-reconciler.development.js:4394
updateClassComponent @ react-reconciler.development.js:8859
beginWork @ react-reconciler.development.js:10500
beginWork$1 @ react-reconciler.development.js:16507
performUnitOfWork @ react-reconciler.development.js:15337
workLoopSync @ react-reconciler.development.js:15268
renderRootSync @ react-reconciler.development.js:15231
performSyncWorkOnRoot @ react-reconciler.development.js:14821
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
index.js:12 Uncaught Could not load studio-small-3/studio_small_03_1k.hdr: Failed to fetch
handleAsset @ index.js:12
useAsset @ index.js:69
useLoader @ react-three-fiber.esm.js:1669
EnvironmentCube @ Environment.js:108
renderWithHooks @ react-reconciler.development.js:6412
mountIndeterminateComponent @ react-reconciler.development.js:9238
beginWork @ react-reconciler.development.js:10476
callCallback @ react-reconciler.development.js:12184
invokeGuardedCallbackDev @ react-reconciler.development.js:12233
invokeGuardedCallback @ react-reconciler.development.js:12292
beginWork$1 @ react-reconciler.development.js:16531
performUnitOfWork @ react-reconciler.development.js:15337
workLoopSync @ react-reconciler.development.js:15268
renderRootSync @ react-reconciler.development.js:15231
performSyncWorkOnRoot @ react-reconciler.development.js:14840
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
next-dev.js:32 The above error occurred in the <EnvironmentCube> component:

    at EnvironmentCube (webpack-internal:///./node_modules/@react-three/drei/core/Environment.js:104:3)
    at Environment (webpack-internal:///./node_modules/@react-three/drei/core/Environment.js:27:16)
    at Suspense
    at Suspense
    at ErrorBoundary (webpack-internal:///./node_modules/@react-three/fiber/dist/react-three-fiber.esm.js:1550:5)
    at Provider (webpack-internal:///./node_modules/@react-three/fiber/dist/react-three-fiber.esm.js:1838:3)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
window.console.error @ next-dev.js:32
logCapturedError @ react-reconciler.development.js:11782
update.payload @ react-reconciler.development.js:11830
getStateFromUpdate @ react-reconciler.development.js:3483
processUpdateQueue @ react-reconciler.development.js:3631
updateClassInstance @ react-reconciler.development.js:4394
updateClassComponent @ react-reconciler.development.js:8859
beginWork @ react-reconciler.development.js:10500
beginWork$1 @ react-reconciler.development.js:16507
performUnitOfWork @ react-reconciler.development.js:15337
workLoopSync @ react-reconciler.development.js:15268
renderRootSync @ react-reconciler.development.js:15231
performSyncWorkOnRoot @ react-reconciler.development.js:14840
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
react-three-fiber.esm.js:1561 Uncaught Could not load studio-small-3/studio_small_03_1k.hdr: Failed to fetch
Canvas @ react-three-fiber.esm.js:1561
renderWithHooks @ react-dom.development.js:14985
updateForwardRef @ react-dom.development.js:17044
beginWork @ react-dom.development.js:19098
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
beginWork$1 @ react-dom.development.js:23964
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
eval @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
componentDidCatch @ react-three-fiber.esm.js:1519
callback @ react-reconciler.development.js:11856
callCallback @ react-reconciler.development.js:3699
commitUpdateQueue @ react-reconciler.development.js:3720
commitLifeCycles @ react-reconciler.development.js:12621
commitLayoutEffects @ react-reconciler.development.js:15993
callCallback @ react-reconciler.development.js:12184
invokeGuardedCallbackDev @ react-reconciler.development.js:12233
invokeGuardedCallback @ react-reconciler.development.js:12292
commitRootImpl @ react-reconciler.development.js:15716
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority @ react-reconciler.development.js:2495
commitRoot @ react-reconciler.development.js:15551
performSyncWorkOnRoot @ react-reconciler.development.js:14857
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
next-dev.js:32 The above error occurred in the <ForwardRef(Canvas)> component:

    at Canvas (webpack-internal:///./node_modules/@react-three/fiber/dist/react-three-fiber.esm.js:1571:3)
    at div
    at ThreeLogo (webpack-internal:///./components/ThreeLogo/index.jsx:241:62)
    at LoadableImpl (webpack-internal:///./node_modules/next/dist/shared/lib/loadable.js:101:38)
    at main
    at Styled.main
    at div
    at Home
    at div
    at VisualElementHandler (webpack-internal:///./node_modules/framer-motion/dist/es/motion/utils/VisualElementHandler.mjs:13:42)
    at MotionComponent (webpack-internal:///./node_modules/framer-motion/dist/es/motion/index.mjs:50:24)
    at PresenceChild (webpack-internal:///./node_modules/framer-motion/dist/es/components/AnimatePresence/PresenceChild.mjs:18:23)
    at AnimatePresence (webpack-internal:///./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs:79:23)
    at LazyMotion (webpack-internal:///./node_modules/framer-motion/dist/es/components/LazyMotion/index.mjs:51:23)
    at div
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:16:20)
    at MyApp (webpack-internal:///./pages/_app.tsx:55:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:357:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:791:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:915:27)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by jamesryan-dev** [comment]
completley rebuilt my app and it;s working - most of been a dusty project causing issues
