### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'elements') - MeshReflectorMaterial

### ISSUE THREAD

**Issue by sovetski** [pmndrs/drei#2138]
- `three` version: 0.169.0
- `@react-three/fiber` version: 9.0.0-alpha.8
- `@react-three/drei` version: 9.115.0
- `node` version: v20.10.0
- `npm` (or `yarn`) version: 10.2.3

### Problem description:

With the code below I am getting this error: `TypeError: Cannot read properties of undefined (reading 'elements')`

### Relevant code:

```jsx
          <mesh position={[0, -1.5, 0]} rotation={[-Math.PI / 2, 0, 0]}>
              <planeGeometry args={[50, 50]} />
              <MeshReflectorMaterial
                  blur={[400, 400]}
                  resolution={1024}
                  mixBlur={1}
                  mixStrength={15}
                  depthScale={1}
                  minDepthThreshold={0.85}
                  color="#dbecfb"
                  metalness={0.6}
                  roughness={1}
              />
          </mesh>
```

**Comment by abernier** [comment]
@sovetski can you paste the error's calls stack?

**Comment by sovetski** [comment]
@abernier sure:

```
TypeError: Cannot read properties of undefined (reading 'elements')
    at Vector3.setFromMatrixPosition (http://localhost:3000/_next/static/chunks/2fd53_three_build_three_module_bcbc2d.js:3488:21)
    at MeshReflectorMaterial.useCallback[beforeRender] (http://localhost:3000/_next/static/chunks/10bfa_@react-three_drei_c48812._.js:1652:36)
    at MeshReflectorMaterial.useFrame [as current] (http://localhost:3000/_next/static/chunks/10bfa_@react-three_drei_c48812._.js:1781:13)
    at update (http://localhost:3000/_next/static/chunks/1303a_@react-three_fiber_dist_b28a6f._.js:2092:26)
    at loop (http://localhost:3000/_next/static/chunks/1303a_@react-three_fiber_dist_b28a6f._.js:2118:23)
```

**Comment by puerschel93** [comment]
Same issue here. @sovetski could you fix it ?

**Comment by samuelkime267** [comment]
Hi guys, I have the same issue here too
Any solution?

`  "@react-three/drei": "^9.120.4",
    "@react-three/fiber": "^9.0.0-rc.1"`

**Comment by israelmitolu** [comment]
I'm having the same issue using Next 15 :/

```
"@react-three/drei": "^9.120.4",
"@react-three/fiber": "9.0.0-alpha.8",
"next": "15.1.2",
"react": "^19.0.0",
"react-dom": "^19.0.0",
```

**Comment by CodyJasonBennett** [comment]
Drei does not support React 19. See #2260 where we're tracking this.
