### ISSUE TITLE
OrbitControls Breaking on SSR - ReferenceError: document is not defined

### ISSUE THREAD

**Issue by saurabhiam** [pmndrs/drei#376]
- `three` version: ^0.128.0
- `@react-three/fiber` ^6.0.16:
- `@react-three/drei` ^4.3.0:
- `node` version: v15.13.0
- `npm` version: 7.7.6
- `OS` macOS 11.2.3

### Problem description:

If OrbitControls are imported from `@react-three/drei` it breaks on Server side rendering throwing error `document is not defined`.

### Relevant code:

```js
import { OrbitControls } from '@react-three/drei';
```

```
/Users/saurabh/Projects/xyz/node_modules/three/build/three.js:25478
                        const image = document.createElementNS('http://www.w3.org/1999/xhtml', 'img');
                                      ^

ReferenceError: document is not defined
    at ImageLoader.load (/Users/saurabh/Projects/xyz/node_modules/three/build/three.js:25478:18)
    at TextureLoader.load (/Users/saurabh/Projects/xyz/node_modules/three/build/three.js:25627:11)
    at Object.<anonymous> (/Users/saurabh/Projects/xyz/node_modules/three-stdlib/index.cjs.js:1:1257398)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/saurabh/Projects/xyz/node_modules/@react-three/drei/index.cjs.js:1:432)
```

### Suggested solution:

Add a window/document check where its referencing three.

I have added tree-shaking into my webpack config to fix the issue and it worked but it should have a required check there else it'll break.

**Comment by joshuaellis** [comment]
As you can see from the error it's coming from `three` not `drei`

**Comment by saurabhiam** [comment]
But can't we just add a document/window check in `drei` where it's referencing `three`?

**Comment by joshuaellis** [comment]
No, AFAIK from others in the org this is a THREE issue and therefore this needs to be resolved in `three`. imo, we shouldn't be hacking these things. Alt you could do a `dynamic` import of the component use `OrbitControls` and include `{ ssr: false }`

**Comment by RenaudRohlinger** [comment]
@saurabhiam See: https://github.com/mrdoob/three.js/pull/21715
