### ISSUE TITLE
Cannot find module '...node_modules/three/examples/jsm/math/MeshSurfaceSampler'

### ISSUE THREAD

**Issue by bramses** [pmndrs/drei#843]
- `three` version: `^0.139.2`
- `@react-three/fiber` version: `^7.0.26`
- `@react-three/drei` version: `8.19.0`
- `node` version: `v14.17.0`
- `npm` (or `yarn`) version: `8.1.1`

### Problem description:

This error happens in NextJS whenever the app is hot reloaded, and is thrown from using `Sampler`

```
Error: Cannot find module '/Users/bram/Desktop/homepage/portfolio-next/node_modules/three/examples/jsm/math/MeshSurfaceSampler'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:912:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:905:15)
    at resolveExports (internal/modules/cjs/loader.js:437:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:477:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:872:27)
    at Function.mod._resolveFilename (/Users/bram/Desktop/homepage/portfolio-next/node_modules/next/dist/build/webpack/require-hook.js:183:28)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/bram/Desktop/homepage/portfolio-next/node_modules/@react-three/drei/index.cjs.js:1:463) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/bram/Desktop/homepage/portfolio-next/node_modules/three/package.json'
}
```

### Relevant code:

```js
<Sampler
          transform={({ position, normal, dummy: object }) => {
            const p = position.clone().multiplyScalar(5)
            const n = Perlin.simplex3(...p.toArray())
            object.scale.setScalar(THREE.MathUtils.mapLinear(n, -1, 1, 0.3, 1) * 0.1)
            object.position.copy(position)
            object.lookAt(normal.add(position))
            object.rotation.y += Math.random() - 0.5 * (Math.PI * 0.5)
            object.rotation.z += Math.random() - 0.5 * (Math.PI * 0.5)
            object.rotation.x += Math.random() - 0.5 * (Math.PI * 0.5)
            object.updateMatrix()
            return object
          }}
          mesh={geomRef}
          instances={meshRef}
        />
```

**Comment by bramses** [comment]
This error also seems to prevent preredering in Vercel:

```
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
--
17:21:11.111 | Error: Cannot find module '/vercel/path0/node_modules/three/examples/jsm/math/MeshSurfaceSampler'
17:21:11.111 | at createEsmNotFoundErr (internal/modules/cjs/loader.js:929:15)
17:21:11.111 | at finalizeEsmResolution (internal/modules/cjs/loader.js:922:15)
17:21:11.111 | at resolveExports (internal/modules/cjs/loader.js:450:14)
17:21:11.112 | at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
17:21:11.112 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
17:21:11.112 | at Function.Module._load (internal/modules/cjs/loader.js:746:27)
17:21:11.112 | at Module.require (internal/modules/cjs/loader.js:974:19)
17:21:11.113 | at require (internal/modules/cjs/helpers.js:101:18)
17:21:11.113 | at Object.<anonymous> (/vercel/path0/node_modules/@react-three/drei/index.cjs.js:1:463)
17:21:11.113 | at Module._compile (internal/modules/cjs/loader.js:1085:14)
```

**Comment by drcmda** [comment]
latest is 9.0.1 i think that takes care of it

**Comment by bramses** [comment]
Next JS is on React17 

> React 18 is now in Release Candidate (RC). Read more about React 18's [release plan](https://reactjs.org/blog/2021/06/08/the-plan-for-react-18.html) and discussions from the [working group](https://github.com/reactwg/react-18/discussions).

[React 18: Overview | Next.js](https://nextjs.org/docs/advanced-features/react-18/overview)

but this version seemed to do the trick: [Release v8.20.2 · pmndrs/drei · GitHub](https://github.com/pmndrs/drei/releases/tag/v8.20.2)
