### ISSUE TITLE
THREE.GLTFLoader: couldn't load texture 

### ISSUE THREAD

**Issue by RichardBrowning** [pmndrs/drei#965]
- "@react-three/drei": "^9.14.3",
- "@react-three/fiber": "^8.0.27",
- "expo": "^45.0.6",
- "expo-gl": "~11.3.0",
- "react": "^18.2.0",
- "react-native": "0.69.1",
- "three": "0.142.0"

- `node` version: v16.15.1
- `npm` (or `yarn`) version: 8.11.0

### Problem description:

EXPO go throws error THREE.GLTFLoader: couldn't load texture
Console error:
```console
Warning: Invalid version react-native@0.69.1 for expo sdkVersion 45.0.0. Use react-native@0.68.2
iOS Running app on iPhone 10
Error: ENOENT: no such file or directory, open '/Users/Shared/GitHub/r3f-native-starter/http:/192.168.1.8:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getCodeFrame (/Users/Shared/GitHub/r3f-native-starter/node_modules/metro/src/Server.js:979:18)
    at Server._symbolicate (/Users/Shared/GitHub/r3f-native-starter/node_modules/metro/src/Server.js:1052:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Server._processRequest (/Users/Shared/GitHub/r3f-native-starter/node_modules/metro/src/Server.js:443:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/Shared/GitHub/r3f-native-starter/http:/192.168.1.8:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false'
}
Error: ENOENT: no such file or directory, open '/Users/Shared/GitHub/r3f-native-starter/http:/192.168.1.8:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at getCodeFrame (/Users/Shared/GitHub/r3f-native-starter/node_modules/metro/src/Server.js:979:18)
    at Server._symbolicate (/Users/Shared/GitHub/r3f-native-starter/node_modules/metro/src/Server.js:1052:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Server._processRequest (/Users/Shared/GitHub/r3f-native-starter/node_modules/metro/src/Server.js:443:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/Shared/GitHub/r3f-native-starter/http:/192.168.1.8:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false'
}
EXGL: gl.pixelStorei() doesn't support this parameter yet!
...
```

### Relevant code:

```js
import React, { Suspense, useEffect, useRef } from 'react'
import { useFrame, Canvas } from '@react-three/fiber/native'
import { useGLTF, Environment, useAnimations } from '@react-three/drei/native'
import idle from './assets/idle.glb'
import fastRun from './assets/fastRun.glb'

function Model({ url, ...rest }) {
  const group = useRef()
  const { scene, nodes, materials, animations } = useGLTF(url)
  useFrame(() => (scene.rotation.y += 0.01))
  const { actions } = useAnimations(animations, group)
  return <primitive {...rest} object={scene} />
}

export default function App() {
  return (
    <Canvas legacy={true} gl={{ physicallyCorrectLights: true }} camera={{ position: [-10, 15, 20], fov: 35}}>
      <color attach="background" args={[0xe2f4df]} />
      <ambientLight />
      <directionalLight intensity={1.1} position={[0.5, 0, 0.866]} />
      <directionalLight intensity={0.8} position={[-6, 2, 2]} />
      <Suspense fallback={null}>
        <Environment preset="park" />
        <Model url={fastRun} />
      </Suspense>
    </Canvas>
  )
}

```

#### The GLTF model used here is generated with Mixamo:

https://user-images.githubusercontent.com/46521212/177020993-892cc3d3-f038-43fc-9441-7d6fda85d6c7.mov

#### The model is originally FBX, convereted into GLTF model with Blender. When displaying in React Native:
![IMG_0275](https://user-images.githubusercontent.com/46521212/177021113-c5ea0086-92fd-47c2-ae4a-7d14c6af1664.PNG)

### Conclusion:
Some other complecated GLTF model does not work. Is there anything to keep in mind when loading complicated models?

**Comment by drcmda** [comment]
@CodyJasonBennett

**Comment by masafumimori** [comment]
hey is there any workaround for this? I have the same issue

**Comment by sepehrg** [comment]
I have the same error

**Comment by CodyJasonBennett** [comment]
This comes from https://github.com/pmndrs/react-three-fiber/issues/1972. react-native doesn't implement critical ArrayBuffer => Blob paths so embedded textures will fail to unpack. I have linked partial implementations of both APIs that need to be stitched together and upstreamed.
